version: '3.9'

services:
  db:
    image: postgres:16
    container_name: python-project-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: python-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:8.0
    container_name: python-project-mongo
    ports:
      - "27017:27017"   # Expose MongoDB default port to host
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db   # Persist data in a named volume

volumes:
  postgres_data:
  mongo_data: